name: whatsapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  bloc: ^8.1.0
  camera: ^0.10.0+4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  emoji_picker_flutter: ^1.5.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  path: ^1.8.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
  video_player: ^2.4.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
